### ISSUE TITLE
Parallelization Bug: multi_scan crashes when `invocation_based_tests` is true

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#113]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

### Issue Description

When `invocation_based_tests` is set to true for the parallelization beta of `multi_scan`, it crashes.

##### Complete output when running fastlane, including the stack trace and command used

```ShellSource
NoMethodError: [!] undefined method `each' for nil:NilClass
  $HOME/.rbenv/gems/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:33:in `quit_simulator'
  $HOME/.rbenv/gems/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:25:in `before_testrun'
  $HOME/.rbenv/gems/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:48:in `run'
  $HOME/.rbenv/gems/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:40:in `run'
  $HOME/.rbenv/gems/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:57:in `run_invocation_based_tests'
  $HOME/.rbenv/gems/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:38:in `run'
  $HOME/.rbenv/gems/fastlane/plugin/test_center/actions/multi_scan.rb:32:in `run'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
  Fastfile:17:in `block (2 levels) in parsing_binding'
  Fastfile:14:in `chdir'
  Fastfile:14:in `block in parsing_binding'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  $HOME/.rbenv/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
  $HOME/.rbenv/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
  $HOME/.rbenv/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
  $HOME/.rbenv/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
  $HOME/.rbenv/gems/fastlane-2.124.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
  $HOME/.rbenv/gems/fastlane-2.124.0/bin/fastlane:23:in `<top (required)>'
```

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.8.0.parallelizing.beta.7](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.8.0.parallelizing.beta.7)
