### ISSUE TITLE
Extension of resultBundlePath has changed in fastlane/scan for Xcode 11

### ISSUE THREAD

**Issue by sdaniel55** [lyndsey-ferguson/fastlane-plugin-test_center#228]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see

> If you love this fastlane plugin, consider sponsoring it or asking your company to sponsor it. I would really appreciate any
> gesture: https://github.com/sponsors/lyndsey-ferguson.

### Issue Description

Action: 
```ruby
multi_scan(
    scheme: scheme,
    try_count: 2,
    fail_build: false,
    derived_data_path: "DerivedData/Debug/#{scheme}",
    device: device,
    devices: devices,
    reset_simulator: true,
    test_without_building: options[:test_without_building].presence,
    only_testing: features,
    skip_testing: skip_testing,
    xcargs: "BRANCH_NAME=\"#{git_branch}\" MILESTONE_ID=\"#{fetch_milestone(options)}\" TESTRUN_ID=\"#{options[:testrun]}\"",
    result_bundle: true,
    include_simulator_logs: false
)
```
Expected behaviour: test results are at `{output_directory}/*.test_result`
Actual behaviour: test results are at `{output_directory}/*.xcresult`

`fastlane/scan` PR changing the extension based on Xcode version: https://github.com/fastlane/fastlane/pull/16044

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>INFO [2020-06-08 16:09:31.06]: $ set -o pipefail && env NSUnbufferedIO=YES xcodebuild -destination 'platform=iOS Simulator,id=B529F270-E436-49CF-B938-8517CC76380E' -derivedDataPath 'DerivedData/Debug/AllTests' -resultBundlePath 'project/fastlane/test_output/project-UITests-batch-1/ProjectAllTests.xcresult' -disable-concurrent-testing -xctestrun 'DerivedData/Debug/ProjectAllTests/Build/Products/ProjectAllTests_iphonesimulator13.1-x86_64.xctestrun' BRANCH_NAME="develop" -parallel-testing-enabled NO -only-testing:Project-UITests/test_case test-without-building | tee '/Users/user/Library/Logs/scan/Project-ProjectAllTests.log' | xcpretty  --report junit --output '/Users/project/fastlane/test_output/Project-UITests-batch-1/report.junit' --report junit --output '/var/folders/pr/1s8tr9g904g4nwbj1k0f6kz0v0753b/T/junit_report20200608-55745-glumbp'

### MORE OUTPUT ###

DEBUG [2020-06-08 16:12:01.47]: Batch #1 incrementing retry count to 1
DEBUG [2020-06-08 16:12:01.47]: Scan passed the tests for batch #1
WARN [2020-06-08 16:12:01.47]: Lane Context:
INFO [2020-06-08 16:12:01.47]: {:DEFAULT_PLATFORM=>:ios, :PLATFORM_NAME=>nil, :LANE_NAME=>"lane_name", :LANE_OPTIONS=>{:scheme=>"ProjectAllTests", :milestone=>"", :testrun=>"", :test_without_building=>true}, :FORCE_NOTIFY_ERROR=>true}
ERROR [2020-06-08 16:12:01.47]: no implicit conversion of nil into String

+------+--------------------------------------------------+-------------+
|                           fastlane summary                            |
+------+--------------------------------------------------+-------------+
| Step | Action                                           | Time (in s) |
+------+--------------------------------------------------+-------------+
| 1    | Verifying fastlane version                       | 0           |
| 2    | default_platform                                 | 0           |
| 3    | ensure_xcode_version                             | 1           |
| 4    | Switch to prepare_simulators_for_ui_testing lane | 0           |
| 5    | killall "Simulator" || true                      | 0           |
| 6    | rm /tmp/simulators.plist || true                 | 0           |
| 7    | git_branch                                       | 0           |
| 💥   | multi_scan                                       | 191         |
+------+--------------------------------------------------+-------------+

ERROR [2020-06-08 16:12:01.53]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: no implicit conversion of nil into String

URL: https://api.github.com/search/issues?q=no%20implicit%20conversion%20of%20nil%20into%20String+repo:fastlane/fastlane
➡️  bundler: failed to load command: fastlane (/usr/local/bin/fastlane) TypeError: [!] no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/16232 [closed] 3 💬
    a week ago

➡️  after update mac os catalina 10.15.4 get [!] no implicit conversion of nil into String (TypeError)
    https://github.com/fastlane/fastlane/issues/16308 [closed] 6 💬
    4 weeks ago

➡️  bundler: failed to load command: fastlane  TypeError: [!] no implicit conversion of nil into String
    https://github.com/fastlane/fastlane/issues/15714 [closed] 6 💬
    24 Mar 2020

and 81 more at: https://github.com/fastlane/fastlane/search?q=no%20implicit%20conversion%20of%20nil%20into%20String&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	41: from /Users/user/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
	40: from /Users/user/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
	39: from /Users/user/.rvm/gems/ruby-2.6.4/bin/fastlane:23:in `<main>'
	38: from /Users/user/.rvm/gems/ruby-2.6.4/bin/fastlane:23:in `load'
	37: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	36: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	35: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	34: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	33: from /Users/user/.rvm/gems/ruby-2.6.4/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	32: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	31: from /Users/user/.rvm/gems/ruby-2.6.4/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	30: from /Users/user/.rvm/gems/ruby-2.6.4/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	29: from /Users/user/.rvm/gems/ruby-2.6.4/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	28: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	27: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	26: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	25: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	24: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	23: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	22: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	21: from Lanes/uitests:77:in `block in parsing_binding'
	20: from Lanes/uitests:449:in `uitest'
	19: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	18: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	17: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	16: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	15: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	14: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	13: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	12: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/actions/multi_scan.rb:24:in `run'
	11: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:53:in `run'
	10: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `run_test_batches'
	 9: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `each_with_index'
	 8: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `each'
	 7: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:143:in `block in run_test_batches'
	 6: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker.rb:18:in `run'
	 5: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:45:in `run'
	 4: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:60:in `run'
	 3: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:125:in `after_testrun'
	 2: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:132:in `handle_success'
	 1: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:302:in `move_test_result_bundle_for_next_run'
/Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:302:in `dirname': no implicit conversion of nil into String (TypeError)
	41: from /Users/user/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
	40: from /Users/user/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
	39: from /Users/user/.rvm/gems/ruby-2.6.4/bin/fastlane:23:in `<main>'
	38: from /Users/user/.rvm/gems/ruby-2.6.4/bin/fastlane:23:in `load'
	37: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/bin/fastlane:23:in `<top (required)>'
	36: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	35: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	34: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	33: from /Users/user/.rvm/gems/ruby-2.6.4/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	32: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	31: from /Users/user/.rvm/gems/ruby-2.6.4/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	30: from /Users/user/.rvm/gems/ruby-2.6.4/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	29: from /Users/user/.rvm/gems/ruby-2.6.4/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	28: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	27: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	26: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	25: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
	24: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	23: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	22: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/lane.rb:33:in `call'
	21: from Lanes/uitests:77:in `block in parsing_binding'
	20: from Lanes/uitests:449:in `uitest'
	19: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	18: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	17: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	16: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	15: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
	14: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	13: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-2.149.1/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
	12: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/actions/multi_scan.rb:24:in `run'
	11: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:53:in `run'
	10: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `run_test_batches'
	 9: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `each_with_index'
	 8: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:140:in `each'
	 7: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:143:in `block in run_test_batches'
	 6: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker.rb:18:in `run'
	 5: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:45:in `run'
	 4: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:60:in `run'
	 3: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:125:in `after_testrun'
	 2: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:132:in `handle_success'
	 1: from /Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:302:in `move_test_result_bundle_for_next_run'
/Users/user/.rvm/gems/ruby-2.6.4/gems/fastlane-plugin-test_center-3.8.11/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan_helper.rb:302:in `dirname': [!] no implicit conversion of nil into String (TypeError)</pre>
</details>

### Environment

<details>
  Note: the log below doesn't use the latest `fastlane-plugin-test_center` version. Did test it, it wasn't failing explicitly, but not reporting any test results
  <pre><details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.15.5                                     |
| Ruby                        | 2.6.4                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.21.0 (Apple Git-122)          |
| Installation Source         | ~/.rvm/gems/ruby-2.6.4/bin/fastlane         |
| Host                        | Mac OS X 10.15.5 (19F101)                   |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.6.4/lib                |
| OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 11.1                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.149.1 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                      | Version | Update-Status      |
| --------------------------- | ------- | ------------------ |
| fastlane-plugin-badge       | 1.3.0   | 🚫 Update available |
| fastlane-plugin-versioning  | 0.3.4   | 🚫 Update available |
| fastlane-plugin-test_center | 3.8.11  | 🚫 Update available |
| fastlane-plugin-appcenter   | 1.5.0   | 🚫 Update available |

<details><summary><b>Loaded gems</b></summary>

| Gem                         | Version      |
| --------------------------- | ------------ |
| did_you_mean                | 1.3.0        |
| executable-hooks            | 1.6.0        |
| bundler-unload              | 1.0.2        |
| rubygems-bundler            | 1.4.5        |
| bundler                     | 2.0.2        |
| rake                        | 13.0.1       |
| CFPropertyList              | 3.0.2        |
| concurrent-ruby             | 1.1.5        |
| i18n                        | 0.9.5        |
| minitest                    | 5.12.2       |
| thread_safe                 | 0.3.6        |
| tzinfo                      | 1.2.5        |
| activesupport               | 4.2.11.1     |
| public_suffix               | 2.0.5        |
| addressable                 | 2.7.0        |
| httpclient                  | 2.8.3        |
| json                        | 2.3.0        |
| algoliasearch               | 1.27.1       |
| atomos                      | 0.1.3        |
| aws-eventstream             | 1.1.0        |
| aws-partitions              | 1.325.0      |
| aws-sigv4                   | 1.1.4        |
| jmespath                    | 1.4.0        |
| aws-sdk-core                | 3.97.1       |
| aws-sdk-kms                 | 1.33.0       |
| aws-sdk-s3                  | 1.67.1       |
| babosa                      | 1.0.3        |
| curb                        | 0.9.10       |
| fastimage                   | 2.1.7        |
| colored                     | 1.2          |
| highline                    | 1.7.10       |
| commander-fastlane          | 4.4.6        |
| dotenv                      | 2.7.5        |
| emoji_regex                 | 1.0.1        |
| excon                       | 0.73.0       |
| multipart-post              | 2.0.0        |
| faraday                     | 0.17.3       |
| unf_ext                     | 0.0.7.7      |
| unf                         | 0.1.4        |
| domain_name                 | 0.5.20190701 |
| http-cookie                 | 1.0.3        |
| faraday-cookie_jar          | 0.0.6        |
| faraday_middleware          | 0.14.0       |
| gh_inspector                | 1.1.3        |
| jwt                         | 2.1.0        |
| memoist                     | 0.16.2       |
| multi_json                  | 1.14.1       |
| os                          | 1.1.0        |
| signet                      | 0.14.0       |
| googleauth                  | 0.12.0       |
| mini_mime                   | 1.0.2        |
| declarative                 | 0.0.10       |
| declarative-option          | 0.1.0        |
| uber                        | 0.1.0        |
| representable               | 3.0.4        |
| retriable                   | 3.1.2        |
| google-api-client           | 0.38.0       |
| digest-crc                  | 0.5.1        |
| google-cloud-env            | 1.3.2        |
| google-cloud-errors         | 1.0.1        |
| google-cloud-core           | 1.5.0        |
| google-cloud-storage        | 1.26.2       |
| mini_magick                 | 4.9.5        |
| multi_xml                   | 0.6.0        |
| plist                       | 3.5.0        |
| rubyzip                     | 1.3.0        |
| security                    | 0.1.3        |
| naturally                   | 2.2.0        |
| simctl                      | 1.6.8        |
| slack-notifier              | 2.3.2        |
| terminal-notifier           | 2.0.0        |
| unicode-display_width       | 1.7.0        |
| terminal-table              | 1.8.0        |
| tty-screen                  | 0.8.0        |
| tty-cursor                  | 0.7.1        |
| tty-spinner                 | 0.9.3        |
| word_wrap                   | 1.0.0        |
| claide                      | 1.0.3        |
| colored2                    | 3.1.2        |
| nanaimo                     | 0.2.6        |
| xcodeproj                   | 1.16.0       |
| rouge                       | 2.0.7        |
| xcpretty                    | 0.3.0        |
| xcpretty-travis-formatter   | 1.0.0        |
| badge                       | 0.11.0       |
| cork                        | 0.3.0        |
| nap                         | 1.1.0        |
| open4                       | 1.3.4        |
| claide-plugins              | 0.9.2        |
| fuzzy_match                 | 2.0.4        |
| cocoapods-core              | 1.8.3        |
| cocoapods-deintegrate       | 1.0.4        |
| cocoapods-downloader        | 1.2.2        |
| cocoapods-plugins           | 1.0.0        |
| cocoapods-search            | 1.0.0        |
| cocoapods-stats             | 1.1.0        |
| netrc                       | 0.11.0       |
| cocoapods-trunk             | 1.4.1        |
| cocoapods-try               | 1.1.0        |
| escape                      | 0.0.4        |
| fourflusher                 | 2.3.1        |
| molinillo                   | 0.6.6        |
| ruby-macho                  | 1.4.0        |
| cocoapods                   | 1.8.3        |
| redcarpet                   | 3.4.0        |
| cocoapods-acknowledgements  | 1.2.0        |
| colorize                    | 0.8.1        |
| faraday-http-cache          | 2.0.0        |
| rchardet                    | 1.8.0        |
| git                         | 1.6.0        |
| kramdown                    | 2.1.0        |
| kramdown-parser-gfm         | 1.1.0        |
| no_proxy_fix                | 0.1.2        |
| sawyer                      | 0.8.2        |
| octokit                     | 4.16.0       |
| danger                      | 6.3.1        |
| thor                        | 0.20.3       |
| danger-swiftlint            | 0.24.1       |
| fastlane-plugin-appcenter   | 1.5.0        |
| fastlane-plugin-badge       | 1.3.0        |
| xctest_list                 | 1.1.8        |
| fastlane-plugin-test_center | 3.8.11       |
| fastlane-plugin-versioning  | 0.3.4        |
| ffi                         | 1.10.0       |
| mustache                    | 0.99.8       |
| rb-fsevent                  | 0.10.3       |
| rb-inotify                  | 0.10.0       |
| sass-listen                 | 4.0.0        |
| sass                        | 3.7.3        |
| sqlite3                     | 1.4.0        |
| liferaft                    | 0.0.6        |
| xcinvoke                    | 0.3.0        |
| jazzy                       | 0.9.3        |
| oauth                       | 0.5.4        |
| jira-ruby                   | 1.6.0        |
| testrail-ruby               | 0.1.02       |
| xcode-install               | 2.6.2        |
</details>

*generated on:* **2020-06-08**
</details></pre>
</details>

**Comment by lyndsey-ferguson** [comment]
Thanks for hunting down the change that broke this! I won't be able to tackle it right away, but I will soon. A temporary fix would be to downgrade the version of fastlane you want to use.

**Comment by sdaniel55** [comment]
@lyndsey-ferguson I can open a PR if you'd like, already fixed it in my forked repo 🙂 just need to figure out how to test it 😄

**Comment by lyndsey-ferguson** [comment]
That would be great! I looked at your change every so briefly and it looks like there may be a possibility of a problem with simply changing the file extension (and yes, I would like logic to be there for checking the version of Xcode as you have done).

The problem, _I think_, is that I think I recall that I make a symbolic link file `.result_bundle` to the actual `.xcresult` bundle as I didn't want to break people's code when they're expecting the `.result_bundle`.  So keep your eye on that. Also, I have spent less than 4 secs thinking/reading about this so I may be way off and everything may just be fine.

**Comment by sdaniel55** [comment]
I think I remember reading about that 🤔 I'll try to look into it a bit more today and make sure this doesn't break anything 🙂
