### ISSUE TITLE
undefined method `map' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Djuise** [lyndsey-ferguson/fastlane-plugin-test_center#325]
### New Issue Checklist

- [x] Updated `fastlane-plugin-test_center` to the latest version
- [x] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [x] I reviewed the [example(s)](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md) for the action(s) I am using
- [x] I have removed any sensitive data such as passwords, authentication tokens, or anything else I do not want to world to see
- [x] I have reviewed the [Discussions forum](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/discussions) to see my question has already been addressed.

I have this lane
```
  lane :tests do
     begin
          test_lane()
          xchtmlreport
       end
  end
  
  def test_lane
    multi_scan(
      fail_build: false,
      try_count: 3,
      workspace: "NotMyProject.xcworkspace",
      scheme: "TestsScheme"
    )
  end
  ```
When I run it, I have errors:
```
🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	47: from /usr/local/bin/fastlane:23:in `<main>'
	46: from /usr/local/bin/fastlane:23:in `load'
	45: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
	44: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	43: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	42: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	41: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	40: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	39: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	38: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	37: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	36: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	35: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	34: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	33: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	31: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	30: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	29: from Fastfile:298:in `block (2 levels) in parsing_binding'
	28: from Fastfile:304:in `testEndToEnd_lane'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/actions/multi_scan.rb:38:in `run'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:108:in `run'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:126:in `setup_run_tests_for_each_device'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:126:in `each_with_index'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:126:in `each'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:137:in `block in setup_run_tests_for_each_device'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:110:in `block in run'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:246:in `run_test_batches'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:246:in `each_with_index'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:246:in `each'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:249:in `block in run_test_batches'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker.rb:18:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:12:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:20:in `run'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:23:in `run'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:65:in `test_app'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/command_executor.rb:90:in `execute'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:74:in `block in test_app'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/error_handler.rb:46:in `handle_build_error'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/ui.rb:17:in `method_missing'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/interface.rb:163:in `build_failure!': Error building/testing the application. See the log above. (FastlaneCore::Interface::FastlaneBuildFailure)
	49: from /usr/local/bin/fastlane:23:in `<main>'
	48: from /usr/local/bin/fastlane:23:in `load'
	47: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/bin/fastlane:23:in `<top (required)>'
	46: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	45: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	44: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	43: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	42: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	41: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	40: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	39: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	38: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	37: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	36: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	35: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	34: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	33: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	32: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	31: from Fastfile:298:in `block (2 levels) in parsing_binding'
	30: from Fastfile:304:in `testEndToEnd_lane'
	29: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	28: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	27: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	26: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	25: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	24: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	23: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	22: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/actions/multi_scan.rb:38:in `run'
	21: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:108:in `run'
	20: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:126:in `setup_run_tests_for_each_device'
	19: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:126:in `each_with_index'
	18: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:126:in `each'
	17: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:137:in `block in setup_run_tests_for_each_device'
	16: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:110:in `block in run'
	15: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:246:in `run_test_batches'
	14: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:246:in `each_with_index'
	13: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:246:in `each'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/runner.rb:249:in `block in run_test_batches'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/test_batch_worker.rb:18:in `run'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:12:in `run'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-plugin-test_center-3.15.1/lib/fastlane/plugin/test_center/helper/multi_scan_manager/retrying_scan.rb:20:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:23:in `run'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:65:in `test_app'
	 6: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane_core/lib/fastlane_core/command_executor.rb:90:in `execute'
	 5: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:72:in `block in test_app'
	 4: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/runner.rb:76:in `rescue in block in test_app'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/scan/lib/scan/slack_poster.rb:46:in `run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/slack.rb:44:in `run'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/slack.rb:212:in `generate_slack_attachments'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.171.0/fastlane/lib/fastlane/actions/slack.rb:190:in `block in generate_slack_attachments': [!] undefined method `map' for nil:NilClass (NoMethodError)
```

When I changed this lane to run_tests (without try_count) everything worked properly.
Could you help me? I checked whole internet and try everything that I found.

**Comment by lyndsey-ferguson** [comment]
Hello, can you provide more information? I have the "New Issue" template set up to guide you on how to provide that information.

![Screen Shot 2021-01-11 at 1 25 05 PM](https://user-images.githubusercontent.com/5741516/104222532-6ecbec00-5410-11eb-8d8c-1b2e461006eb.png)

**Comment by lyndsey-ferguson** [comment]
Closing this issue due to lack of response and data
