### ISSUE TITLE
Regression on fastlane 2.201.rc2

### ISSUE THREAD

**Issue by Kylmakalle** [lyndsey-ferguson/fastlane-plugin-test_center#374]
### Regression Information

- Breaking version: [e.g. `2.201.0.rc2`]
- Last working version: [e.g. `2.200.0`]

### Regression Description

I'm using multi_scan and recent release candidate of fastlane breaks plugin.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>bundler: failed to load command: fastlane (/Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/fastlane)
TypeError: [0;31;49m[!] no implicit conversion of nil into String[0m
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/trainer-0.9.1/lib/trainer/test_parser.rb:49:in `gsub'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/trainer-0.9.1/lib/trainer/test_parser.rb:49:in `block in auto_convert'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/trainer-0.9.1/lib/trainer/test_parser.rb:36:in `each'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/trainer-0.9.1/lib/trainer/test_parser.rb:36:in `auto_convert'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/scan/lib/scan/runner.rb:211:in `trainer_test_results'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/scan/lib/scan/runner.rb:222:in `handle_results'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/scan/lib/scan/runner.rb:23:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:251:in `build_for_testing'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:204:in `prepare_for_testing'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/fastlane-plugin-test_center-3.15.3/lib/fastlane/plugin/test_center/actions/multi_scan.rb:25:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/other_action.rb:23:in `method_missing'
  /Users/user/builds/Z1z9ygUP/0/app-my-app/ios/my-app-ios/fastlane/actions/*****/*******.rb:50:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:229:in `chdir'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
  Fastfile:352:in `block (2 levels) in parsing_binding'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/commands_generator.rb:109:in `block (2 levels) in run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:117:in `run!'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/commands_generator.rb:353:in `run'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/fastlane/lib/fastlane/cli_tools_distributor.rb:122:in `take_off'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bundler/gems/fastlane-565255f8b185/bin/fastlane:23:in `<top (required)>'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/fastlane:23:in `load'
  /Users/user/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/bin/fastlane:23:in `<top (required)>'</pre>
</details>

**Comment by lyndsey-ferguson** [comment]
I want to apologize that I have not responded to this issue. A family health issue is requiring me to narrow my focus on the essentials and I don't have the time I need to focus on the plugin more than a minute.  This has an active PR that hopefully the community can rally around and get it ready for merge.
