### ISSUE TITLE
multi_scan crashes when there are no html report files

### ISSUE THREAD

**Issue by lyndsey-ferguson** [lyndsey-ferguson/fastlane-plugin-test_center#54]
### New Issue Checklist

- [ ] Updated `fastlane-plugin-test_center` to the latest version
- [ ] I read the [README.md](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/README.md)
- [ ] I reviewed the example [Fastfile](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/blob/master/fastlane/Fastfile)

### Issue Description

```
bundler: failed to load command: fastlane (/Users/XYZ-ci/.rbenv/versions/2.3.0/bin/fastlane)
TypeError: �[31m[!] no implicit conversion from nil to integer�[0m
  /Users/XYZ-ci/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-plugin-test_center-3.2.4/lib/fastlane/plugin/test_center/helper/reportname_helper.rb:81:in `[]'
  /Users/XYZ-ci/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-plugin-test_center-3.2.4/lib/fastlane/plugin/test_center/helper/reportname_helper.rb:81:in `html_last_reportname'
  /Users/XYZ-ci/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/fastlane-plugin-test_center-3.2.4/lib/fastlane/plugin/test_center/helper/correcting_scan_helper.rb:173:in `testrun_info'
```
##### An example of how the `test_center` action is being called.

```
  multi_scan(scheme: "Smoke Tests",
                     devices: ["iPhone 8"],
                     clean: true,
                     output_types: "junit",
                     try_count: 3)
```
##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

### Environment

<details>
  <pre>[INSERT OUTPUT HERE]</pre>
</details>

**Comment by lyndsey-ferguson** [comment]
Fixed in [v3.2.5](https://github.com/lyndsey-ferguson/fastlane-plugin-test_center/releases/tag/v3.2.5)
